[package]
name = "uigf"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1", features = ["serde_derive"] }
serde_json = "1"
serde_with = { version = "3.9.0", features = ["macros"] }
